# Generated by Django 2.2.1 on 2019-05-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basesite', '0003_auto_20190517_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='slug',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='З/П'),
        ),
    ]
