# Generated by Django 2.2.1 on 2019-05-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basesite', '0007_delete_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviwes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Имя')),
                ('body', models.TextField(blank=True, db_index=True)),
            ],
        ),
    ]
