# Generated by Django 2.2.1 on 2019-05-27 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basesite', '0008_reviwes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviwes',
            new_name='Reviews',
        ),
    ]
