# Generated by Django 2.2.1 on 2019-05-07 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название:')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Название:')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена:')),
                ('active', models.BooleanField(default=True)),
                ('type_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basesite.TypeWork')),
            ],
        ),
    ]
